### ISSUE TITLE
Replace File System storage w/ DB

### ISSUE THREAD

**Issue by cmc333333** [18F/eregs-platform#13]
The parser's "index" is currently stored within the file system. As we want that index to last in between deploys and be shared across instances, we need to use a shared database.

Components:
- [x] Requests Cache eregs/regulations-parser#289
- [x] Dependency Graph eregs/regulations-parser#291
- [x] Local XML repo eregs/regulations-parser#293
- [x] Use HTTP rather than filesystem for modified files eregs/regulations-parser#296
- [x] Index entries (binaries) eregs/regulations-parser#297

**Comment by cmc333333** [comment]
Quick progress note that I'm working on the last entry here (storing the file contents in the database), but don't think I'll get a pull request in time for the sprint.

**Comment by cmc333333** [comment]
All merged
